let name = "Alice";
let age = 30;
let isStudent = false;
console.log("Initial Values:");
console.log("Name: " + name);
console.log("Age: " + age);
console.log("Is Student: " + isStudent);
name = "Bob";
age += 1;
isStudent = !isStudent;
console.log("\nUpdated Values:");
console.log("Name: " + name);
console.log("Age: " + age);
console.log("Is Student: " + isStudent);